<a href="https://colab.research.google.com/github/Sherzod19s/ECON3086-Python-Programming-for-FinTech/blob/main/ex9a_basic_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 9a - Basic operations with dataframe

Using the yfinance library to get Microsoft Stock data of past 5 years.

In [64]:
import pandas as pd
import yfinance as yf

# Get MSFT stock data for the last 5 years using history method
msft_ticker = yf.Ticker('MSFT')
msft = msft_ticker.history(period="5y")

In [65]:
msft

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-03-25 00:00:00-04:00,225.784379,227.358057,222.205226,222.944077,34061900,0.0,0.0
2021-03-26 00:00:00-04:00,222.186020,227.137350,222.186020,226.916641,25479900,0.0,0.0
2021-03-29 00:00:00-04:00,227.022157,227.223671,222.502641,225.726761,25227500,0.0,0.0
2021-03-30 00:00:00-04:00,224.085976,224.393042,221.754253,222.473923,24792000,0.0,0.0
2021-03-31 00:00:00-04:00,223.491071,229.430748,222.992096,226.235413,43623500,0.0,0.0
...,...,...,...,...,...,...,...
2026-03-18 00:00:00-04:00,397.130005,398.000000,391.000000,391.790009,25908500,0.0,0.0
2026-03-19 00:00:00-04:00,390.100006,392.489990,387.059998,389.019989,25138800,0.0,0.0
2026-03-20 00:00:00-04:00,386.790009,387.000000,380.119995,381.869995,50853200,0.0,0.0
2026-03-23 00:00:00-04:00,383.899994,387.209991,381.679993,383.000000,29680100,0.0,0.0
2026-03-24 00:00:00-04:00,382.410004,382.470001,371.850006,372.739990,40186581,0.0,0.0

Q1. List the Index

In [66]:
msft.index

DatetimeIndex(['2021-03-25 00:00:00-04:00', '2021-03-26 00:00:00-04:00',
               '2021-03-29 00:00:00-04:00', '2021-03-30 00:00:00-04:00',
               '2021-03-31 00:00:00-04:00', '2021-04-01 00:00:00-04:00',
               '2021-04-05 00:00:00-04:00', '2021-04-06 00:00:00-04:00',
               '2021-04-07 00:00:00-04:00', '2021-04-08 00:00:00-04:00',
               ...
               '2026-03-11 00:00:00-04:00', '2026-03-12 00:00:00-04:00',
               '2026-03-13 00:00:00-04:00', '2026-03-16 00:00:00-04:00',
               '2026-03-17 00:00:00-04:00', '2026-03-18 00:00:00-04:00',
               '2026-03-19 00:00:00-04:00', '2026-03-20 00:00:00-04:00',
               '2026-03-23 00:00:00-04:00', '2026-03-24 00:00:00-04:00'],
              dtype='datetime64[ns, America/New_York]', name='Date', length=1255, freq=None)

Q2. List the Columns Name

In [67]:
msft.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

Q3. Filter the dataframe to get the data of 2024 only.

In [68]:
msft_2024 = msft[msft.index.year == 2024]
msft_2024

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-02 00:00:00-05:00,367.528834,369.534296,360.558903,364.589478,25258600,0.0,0.0
2024-01-03 00:00:00-05:00,362.760935,366.938962,362.269402,364.324005,23083500,0.0,0.0
2024-01-04 00:00:00-05:00,364.392824,366.781666,360.952096,361.709045,20901500,0.0,0.0
2024-01-05 00:00:00-05:00,362.721619,365.759287,360.293446,361.522278,21004600,0.0,0.0
2024-01-08 00:00:00-05:00,363.046020,368.846130,362.760953,368.344757,23134000,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-24 00:00:00-05:00,430.484608,435.387183,430.029025,435.119751,7164500,0.0,0.0
2024-12-26 00:00:00-05:00,434.872113,436.714303,432.445610,433.911407,8194200,0.0,0.0
2024-12-27 00:00:00-05:00,430.435086,431.049140,422.264149,426.404083,18117700,0.0,0.0
2024-12-30 00:00:00-05:00,421.976921,423.452632,417.856784,420.758698,13158700,0.0,0.0
2024-12-31 00:00:00-05:00,422.016555,422.640522,416.628686,417.460632,13246500,0.0,0.0

Q4 Filter the dataframe to get the data of Mar 2023.

In [69]:
msft_march_2023 = msft[(msft.index.year == 2023) & (msft.index.month == 3)]
msft_march_2023

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-03-01 00:00:00-05:00,244.958888,245.124953,240.103863,240.572769,27565300,0.0,0.0
2023-03-02 00:00:00-05:00,240.846260,245.584051,239.928004,245.300766,24808200,0.0,0.0
2023-03-03 00:00:00-05:00,246.355804,249.706447,245.574308,249.384079,30760100,0.0,0.0
2023-03-06 00:00:00-05:00,250.497743,254.102381,250.058156,250.927567,24109800,0.0,0.0
2023-03-07 00:00:00-05:00,250.370702,251.728560,247.528034,248.270447,21473200,0.0,0.0
2023-03-08 00:00:00-05:00,248.163002,248.651435,245.007730,247.830872,17340200,0.0,0.0
2023-03-09 00:00:00-05:00,249.901849,253.555318,245.759932,246.482819,26653400,0.0,0.0
2023-03-10 00:00:00-05:00,245.271467,246.941899,241.871978,242.839066,28333900,0.0,0.0
2023-03-13 00:00:00-04:00,241.676622,251.943492,240.045257,248.045792,33339700,0.0,0.0
2023-03-14 00:00:00-04:00,250.810350,255.030418,249.940940,254.756897,33620300,0.0,0.0
2023-03-15 00:00:00-04:00,253.965606,260.315235,253.213401,259.299286,46028000,0.0,0.0
2023-03-16 00:00:00-04:00,259.074617,270.162052,257.189273,269.810394,54768800,0.0,0.0
2023-03-17 00:00:00-04:00,271.822690,276.775377,269.927568,272.965607,69527400,0.0,0.0
2023-03-20 00:00:00-04:00,270.572334,271.060767,263.607275,265.932220,43466600,0.0,0.0
2023-03-21 00:00:00-04:00,268.520909,268.638128,263.284892,267.446350,34558700,0.0,0.0
2023-03-22 00:00:00-04:00,267.075121,274.538391,265.883343,265.990814,34873300,0.0,0.0
2023-03-23 00:00:00-04:00,271.510094,274.557910,268.833491,271.236572,36610900,0.0,0.0
2023-03-24 00:00:00-04:00,270.826244,274.137833,268.911596,274.079224,28172000,0.0,0.0
2023-03-27 00:00:00-04:00,274.010827,274.948610,269.146025,269.986145,26840200,0.0,0.0
2023-03-28 00:00:00-04:00,269.409866,269.751775,265.756367,268.862823,21878600,0.0,0.0
2023-03-29 00:00:00-04:00,272.506500,274.636091,271.969236,274.020660,25087000,0.0,0.0
2023-03-30 00:00:00-04:00,277.654588,277.879248,274.968207,277.478729,25053400,0.0,0.0
2023-03-31 00:00:00-04:00,277.166148,282.577963,276.453025,281.630402,32766000,0.0,0.0

Q5.
- Create a new column "Intraday Price Change" where the value is Close price - Open price
- Create a new column "Price Change" where the value is Close price - last trading day Close price
- Create a new column "Percentage change" where the value is close price / last trading day close price - 1

In [70]:
msft['Intraday Price Change'] = msft['Close']-msft['Open']
msft['Price Change'] = msft['Close']-msft['Close'].shift(1)
msft['Percentage change'] = msft['Close']/msft['Close'].shift(1)-1

Q6. Check whether there were any dividend within the data

In [71]:
msft[msft['Dividends'] > 0]['Dividends']

Date
2021-05-19 00:00:00-04:00    0.56
2021-08-18 00:00:00-04:00    0.56
2021-11-17 00:00:00-05:00    0.62
2022-02-16 00:00:00-05:00    0.62
2022-05-18 00:00:00-04:00    0.62
2022-08-17 00:00:00-04:00    0.62
2022-11-16 00:00:00-05:00    0.68
2023-02-15 00:00:00-05:00    0.68
2023-05-17 00:00:00-04:00    0.68
2023-08-16 00:00:00-04:00    0.68
2023-11-15 00:00:00-05:00    0.75
2024-02-14 00:00:00-05:00    0.75
2024-05-15 00:00:00-04:00    0.75
2024-08-15 00:00:00-04:00    0.75
2024-11-21 00:00:00-05:00    0.83
2025-02-20 00:00:00-05:00    0.83
2025-05-15 00:00:00-04:00    0.83
2025-08-21 00:00:00-04:00    0.83
2025-11-20 00:00:00-05:00    0.91
2026-02-19 00:00:00-05:00    0.91
Name: Dividends, dtype: float64

Q7. Remove the column "Dividends" from the dataframe

In [72]:
msft = msft.drop('Dividends', axis=1)
msft

,Open,High,Low,Close,Volume,Stock Splits,Intraday Price Change,Price Change,Percentage change
Date,,,,,,,,,
2021-03-25 00:00:00-04:00,225.784379,227.358057,222.205226,222.944077,34061900,0.0,-2.840303,NaN,NaN
2021-03-26 00:00:00-04:00,222.186020,227.137350,222.186020,226.916641,25479900,0.0,4.730622,3.972565,0.017819
2021-03-29 00:00:00-04:00,227.022157,227.223671,222.502641,225.726761,25227500,0.0,-1.295396,-1.189880,-0.005244
2021-03-30 00:00:00-04:00,224.085976,224.393042,221.754253,222.473923,24792000,0.0,-1.612053,-3.252838,-0.014411
2021-03-31 00:00:00-04:00,223.491071,229.430748,222.992096,226.235413,43623500,0.0,2.744342,3.761490,0.016908
...,...,...,...,...,...,...,...,...,...
2026-03-18 00:00:00-04:00,397.130005,398.000000,391.000000,391.790009,25908500,0.0,-5.339996,-7.619995,-0.019078
2026-03-19 00:00:00-04:00,390.100006,392.489990,387.059998,389.019989,25138800,0.0,-1.080017,-2.770020,-0.007070
2026-03-20 00:00:00-04:00,386.790009,387.000000,380.119995,381.869995,50853200,0.0,-4.920013,-7.149994,-0.018380
2026-03-23 00:00:00-04:00,383.899994,387.209991,381.679993,383.000000,29680100,0.0,-0.899994,1.130005,0.002959
2026-03-24 00:00:00-04:00,382.410004,382.470001,371.850006,372.739990,40186581,0.0,-9.670013,-10.260010,-0.026789

Q8. Find the highest stock price ever in this period, and find the date of it

In [73]:
msft.loc[msft['Close'].idxmax()]

Open                     5.477224e+02
High                     5.514270e+02
Low                      5.385307e+02
Close                    5.398253e+02
Volume                   2.998670e+07
Stock Splits             0.000000e+00
Intraday Price Change   -7.897154e+00
Price Change             1.050629e+01
Percentage change        1.984869e-02
Name: 2025-10-28 00:00:00-04:00, dtype: float64

Q9. Find the highest volume date

In [74]:
msft.loc[msft['Volume'].idxmax()]

Open                     4.389880e+02
High                     4.414923e+02
Low                      4.200612e+02
Close                    4.325128e+02
Volume                   1.288553e+08
Stock Splits             0.000000e+00
Intraday Price Change   -6.475211e+00
Price Change            -4.802039e+01
Percentage change       -9.993146e-02
Name: 2026-01-29 00:00:00-05:00, dtype: float64

Q10. Find the top 20 highest price percentage change date and it's percentage change, order in decending order.

In [75]:
msft_20 = msft['Percentage change'].sort_values(ascending=False).head(20)
msft_20

Date
2025-04-09 00:00:00-04:00    0.101337
2022-11-10 00:00:00-05:00    0.082268
2025-05-01 00:00:00-04:00    0.076254
2023-04-26 00:00:00-04:00    0.072435
2022-07-27 00:00:00-04:00    0.066852
2022-11-30 00:00:00-05:00    0.061623
2022-02-24 00:00:00-05:00    0.051094
2022-04-27 00:00:00-04:00    0.048109
2023-02-02 00:00:00-05:00    0.046884
2022-03-09 00:00:00-05:00    0.045858
2021-10-27 00:00:00-04:00    0.042115
2023-02-07 00:00:00-05:00    0.042022
2025-01-22 00:00:00-05:00    0.041307
2023-03-16 00:00:00-04:00    0.040537
2022-10-28 00:00:00-04:00    0.040221
2023-07-18 00:00:00-04:00    0.039800
2025-07-31 00:00:00-04:00    0.039475
2022-10-17 00:00:00-04:00    0.039246
2022-03-15 00:00:00-04:00    0.038742
2023-05-25 00:00:00-04:00    0.038458
Name: Percentage change, dtype: float64